### ISSUE TITLE
Compatibility with Jest 25

### ISSUE THREAD

**Issue by minhphl** [nfour/fermenter#27]
# Description

Run test suite using `jest@24.5.0`, this warning is displayed:

```bash
Test suite failed to run
      
          Returning a Promise from "describe" is not supported. Tests must be defined synchronously.
          Returning a value from "describe" will fail the test in a future version of Jest.
      
        // file content
      
            at addSpecsToSuite (node_modules/jest-config/node_modules/jest-jasmine2/build/jasmine/Env.js:425:15)
            at describeFeature (packages/feature-suite/node_modules/fermenter/Feature.js:50:13)
            at Feature (packages/feature-suite/node_modules/fermenter/Feature.js:21:5)
            at Object.<anonymous> (packages/feature-suite/specification.feat.js:10:1)
```

That warning will become a runtime exception in `jest@25`. Source: https://github.com/facebook/jest/blob/e08be020e9ddcab5b89cd871a2cbd72f006cda7b/packages/jest-jasmine2/src/jasmine/Env.ts#L427

# Suggestion

Remove `async` signature in the callback at https://github.com/nfour/fermenter/blob/0a1423da16c49be83440fddf4809b21fa0034599/src/Feature.ts#L97
There's nothing inside that needs `await` anyway.

**Comment by nfour** [comment]
Thanks, will fix this momentarily!
